---
- name: "Deploy Flask"
  hosts: '{{ host }}'
  #remote_user: ubuntu
  tasks:
      - name: setup nginx remote
        apt:
            pkg:
            - gnupg2
            - ca-certificates
        become: yes

      - name: add apt source
        copy:
            dest: /etc/apt/sources.list.d/nginx.list
            content: "deb http://nginx.org/packages/ubuntu bionic nginx"
        become: yes
        become_user: root

      - name: add nginx signing key
        apt_key:
            url: https://nginx.org/keys/nginx_signing.key
            state: present
        become: yes

      - name: install python and nginx packages
        apt:
            pkg:
            - python3
            - python3-pip
            - python3-setuptools
            - nginx
            update_cache: yes
        become: yes

      - name: install Flask
        pip:
            name: Flask
...

