---
- name: "Deploy Flask"
  hosts: '{{ host }}'
  #remote_user: ubuntu
  tasks:
      - name: install python and nginx packages
        apt:
            pkg:
            - python3
            - python3-pip
            - python3-setuptools
            update_cache: yes
        become: yes

      - name: install Flask and virtualenv
        pip:
            name:
                - Flask
                - virtualenv
...

