---
# Assumes you have run the flask.yml playbook already
- name: "Deploy Git Flask Project"
  hosts: '{{ host }}'
  remote_user: '{{ user }}'
  tasks:
      #      - name: add github.com to known hosts
      #        shell: ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts
      #        become: yes

      - name: install git as needed
        apt:
            name: git
            state: present
            update_cache: yes
        become: yes

      - name: clone repo
        git:
            repo: "{{ repo_name }}"
            dest: "/home/{{user}}/repo"
            accept_hostkey: yes

      - name: create virtualenv directory
        file:
            path: "/home/{{user}}/venvs"
            owner: "ubuntu"
            state: directory
        become: yes

      - name: install dependencies
        pip:
            requirements: "/home/{{user}}/repo/requirements.txt"
            virtualenv: "/home/{{user}}/venvs/service"
            virtualenv_python: python3.6

      - name: copy nginx.conf file
        copy:
            src: "/home/{{user}}/repo/config/nginx.conf"
            dest: /etc/nginx/nginx.conf
            remote_src: yes
        become: yes

      - name: find gunicorn service file
        find:
            paths: "/home/{{user}}/repo/config/"
            patterns: "*.service"
        register: gunicorn_result

      - name: copy gunicorn service file
        copy:
            src: "{{ gunicorn_result.files[0]['path'] }}"
            dest: /etc/systemd/system/
            remote_src: yes
        become: yes

      - name: create log directory
        file:
            path: /var/log/gunicorn
            owner: "ubuntu"
            group: "root"
            state: directory
        become: yes

      - name: create symlink from repo to gunicorn logs
        file:
            src: /var/log/gunicorn
            dest: "/home/{{user}}/repo"
            owner: "ubuntu"
            state: link
        become: yes
...

