---
- name: "Start nginx and gunicorn services"
  hosts: '{{ host }}'
  remote_user: '{{ user }}'
  tasks:
      - name: restart nginx
        command: nginx -s reload
        become: yes

      - name: find gunicorn service file
        find:
            paths: "/home/{{user}}/repo/config/"
            patterns: "*.service"
        register: gunicorn_result

      - name: restart gunicorn
		systemd:
			state: restarted
			name: "{{ gunicorn_result.files[0]['path'] | basename }}"
        become: yes
...

