---
- name: "Check gunicorn service status"
  hosts: '{{ host }}'
  remote_user: '{{ user }}'
  tasks:
      - name: find gunicorn service file
        find:
            paths: "/home/{{user}}/repo/config/"
            patterns: "*.service"
        register: gunicorn_result

      - name: get gunicorn status
        command: "systemctl status {{ gunicorn_result.files[0]['path'] | basename }}"
        become: yes
        register: output

      - name: result
        debug:
          var: output.stdout_lines
...

